### ISSUE TITLE
单机4卡3090训练lora报错

### ISSUE THREAD

**Issue by 1006076811** [hiyouga/ChatGLM-Efficient-Tuning#371] opened 2023-07-31 06:36 UTC
报错信息如下：
Traceback (most recent call last):                                                                                                                                                                                                 
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 21, in <module>
    main()
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 25, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/dsets/preprocess.py", line 139, in preprocess_dataset
    print_sft_dataset_example(dataset[0])
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2792, in __getitem__
    return self._getitem(key)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2776, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 0 is out of bounds for size 0
Traceback (most recent call last):                                                                                                                                                                                                 
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 21, in <module>
    main()
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 25, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/dsets/preprocess.py", line 139, in preprocess_dataset
    print_sft_dataset_example(dataset[0])
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2792, in __getitem__
    return self._getitem(key)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2776, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)                                                                                                                                                                                              
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
Traceback (most recent call last):
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 21, in <module>
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 0 is out of bounds for size 0
    main()
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 25, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/dsets/preprocess.py", line 139, in preprocess_dataset
    print_sft_dataset_example(dataset[0])
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2792, in __getitem__
    return self._getitem(key)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2776, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 0 is out of bounds for size 0
Traceback (most recent call last):                                                                                                                                                                                                 
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 21, in <module>
    main()
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 25, in run_sft
    dataset = preprocess_dataset(dataset, tokenizer, data_args, training_args, stage="sft")
  File "/home/ducheng/PycharmProjects/ChatGLM-Efficient-Tuning/src/glmtuner/dsets/preprocess.py", line 139, in preprocess_dataset
    print_sft_dataset_example(dataset[0])
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2792, in __getitem__
    return self._getitem(key)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2776, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 526, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 0 is out of bounds for size 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18345) of binary: /home/ducheng/anaconda3/envs/chatglm/bin/python
Traceback (most recent call last):
  File "/home/ducheng/anaconda3/envs/chatglm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 964, in launch_command
    deepspeed_launcher(args)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ducheng/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../src/train_bash.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-31_14:32:49
  host      : ducheng-server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 18346)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-07-31_14:32:49
  host      : ducheng-server
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 18347)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-07-31_14:32:49
  host      : ducheng-server
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 18348)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-31_14:32:49
  host      : ducheng-server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 18345)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by hiyouga** [comment] 2023-07-31 06:49
数据集定义有误

**Comment by lrx1213** [comment] 2023-08-04 02:24
> 

应该不是数据集问题，我的单机双卡可以正常训练，单机四卡也报了类似的错误。
[INFO|modeling_utils.py:2600] 2023-08-04 10:16:07,761 >> loading weights file ../Model/chatglm2-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:599] 2023-08-04 10:16:07,766 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.31.0"
}

Loading checkpoint shards:  71%|██████████████████████████████████████████████████████████████████████████████████████████                                    | 5/7 [00:25<00:11,  5.82s/it]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27287 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27288 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27290 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 27289) of binary: /usr/local/anaconda3/envs/chatglm_et/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/chatglm_et/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
src/train_bash.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-04_10:16:41
  host      : nb-lizongshang-lzs-im2.ea-app-headless-service.techdata-gxjs-yyjs-cd.svc.bcc-lf2.jd.local
  rank      : 2 (local_rank: 2)
  exitcode  : -9 (pid: 27289)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 27289
============================================================

**Comment by 1006076811** [comment] 2023-08-04 03:21
> > 
> 
> 应该不是数据集问题，我的单机双卡可以正常训练，单机四卡也报了类似的错误。 [INFO|modeling_utils.py:2600] 2023-08-04 10:16:07,761 >> loading weights file ../Model/chatglm2-6b/pytorch_model.bin.index.json [INFO|configuration_utils.py:599] 2023-08-04 10:16:07,766 >> Generate config GenerationConfig { "_from_model_config": true, "eos_token_id": 2, "pad_token_id": 0, "transformers_version": "4.31.0" }
> 
> # Loading checkpoint shards: 71%|██████████████████████████████████████████████████████████████████████████████████████████ | 5/7 [00:25<00:11, 5.82s/it]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27287 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27288 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27290 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 27289) of binary: /usr/local/anaconda3/envs/chatglm_et/bin/python
> Traceback (most recent call last):
> File "/usr/local/anaconda3/envs/chatglm_et/bin/accelerate", line 8, in
> sys.exit(main())
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
> args.func(args)
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
> multi_gpu_launcher(args)
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
> distrib_run.run(args)
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
> elastic_launch(
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/usr/local/anaconda3/envs/chatglm_et/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## src/train_bash.py FAILED
> ## Failures:
> <NO_OTHER_FAILURES>
> # Root Cause (first observed failure):
> [0]:
> time : 2023-08-04_10:16:41
> host : nb-lizongshang-lzs-im2.ea-app-headless-service.techdata-gxjs-yyjs-cd.svc.bcc-lf2.jd.local
> rank : 2 (local_rank: 2)
> exitcode : -9 (pid: 27289)
> error_file: <N/A>
> traceback : Signal 9 (SIGKILL) received by PID 27289

我这个确实是数据集的问题，我自定义的数据集把提问放到input里了，instruction为空导致的这个错误，后来把instruction设置了内容就可以正常训练了

**Closed** 2023-08-04 03:21 UTC
Labels: pending
